### ISSUE TITLE
Contributor request

### ISSUE THREAD

**Issue by rajzshkr** [5thingsAngular/5thingsAngular.github.io#3]
I am glad to help in building website for 5thingsAngular. Just wanna contribute my part for angular community.

**Comment by PascalPrecht** [comment]
Hey @rajzshkr that's awesome! Did you have anything particular in mind?

**Comment by rajzshkr** [comment]
I can help out in building website for 5thingsAngular.

**Comment by PascalPrecht** [comment]
Hey @rajzshkr sorry it took me so so so long to reply. Haven't looked into issues here for quite a while.

You are very welcome to help out with the website. How about you throw in your idea on how to improve it?
